### ISSUE TITLE
Add a payment method field in the condition matrix

### ISSUE THREAD

**Issue by peterjaap** [aune-io/magento2-autoinvoice#1]
We've built a Magento 1 AutoInvoice extension where we've added Payment Method into the mix. This allows us to automatically invoice orders with a certain payment method/status combination.

Here's a screenshot;

![image](https://user-images.githubusercontent.com/431360/27226026-43faf750-529d-11e7-810d-e6319d6c5098.png)

It would be great to have this option in this extension as well.

**Comment by renatocason** [comment]
Hi @peterjaap ,

That's definitely a good point, as well as the status update.
I will pick this up as soon as I have some time in the next days!

Regards,
Renato

**Comment by renatocason** [comment]
Hi @peterjaap ,

It took definitely more than expected :)
I had the feature branch here for a while, but I had the chance to test it properly only today.
Now the module supports more options: you can pick status/payment method combinations as condition, and set the destination status.
Let me know what you think!

Regards,
Renato

**Comment by peterjaap** [comment]
@renatocason fantastic, thanks! We'll look into it :)
