### ISSUE TITLE
Can't install on Magento 2.2.6

### ISSUE THREAD

**Issue by fballiano** [aune-io/magento2-autoinvoice#11]
Hi Renato,
if I just run "composer require aune-io/magento2-autoinvoice" on a M2.2 I get errors because the magento/framework is not version 102 but 101.

shoud I install an older version of the module?

**Comment by renatocason** [comment]
Hi @fballiano ,

My apologies, when I tested M2.3 support I accidentally replaced the dependencies versions instead of adding them. I just created a new release, 2.0.1, which should work for you. Let me know!

Thanks,
Renato

**Comment by fballiano** [comment]
thanks @renatocason, it now works perfectly!
