### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by nordcomputer** [aune-io/magento2-autoinvoice#14]
So, would this module work with php 7.4? Thats a dependency for magento 2.4....

**Comment by renatocason** [comment]
Hi @nordcomputer ,

Personally, I never tested this extension with PHP 7.4 / Magento 2.4.
But, if you have a chance, you are free and more than welcome to provide feedback and, maybe, a PR to fix any issue you might encounter.

Thanks,
Renato

**Comment by nordcomputer** [comment]
Ok, I am on it....

**Comment by peterjaap** [comment]
See #15

**Comment by renatocason** [comment]
Thanks for your contribution @peterjaap ! Version 2.1.1 released.

Regards,
Renato
