### ISSUE TITLE
Multiple stores / websites

### ISSUE THREAD

**Issue by tniemi** [aune-io/magento2-autoinvoice#19]
I had a strange problem that I could not see any of the payment methods. I had klarna payments enabled in the global level and in the 5 websites, but not in the default ( website id 1 / english ), so it took a while to notice that all the payment methods comes from the default website id = 1 ( in my case that is the default ) and not from the global/admin or anywhere else, only from the default. Would be great if it would get payment methods from the global level ( as it is possible to enable all the payment methods on global level and disable on the websites ) or that it could be used per website :)

**Comment by renatocason** [comment]
Hi @tniemi ,

A quick workaround could be to enable all payment methods on default and disable them on the website they are not needed in.
If that doesn't work for you, you are welcome to fork the extension and adapt it to your needs. Then, if you think your changes could benefit others, you can open a PR for them to be included here.

Good luck!
