### ISSUE TITLE
Undefined variable: email

### ISSUE THREAD

**Issue by taskula** [aune-io/magento2-autoinvoice#20]
I upgraded this module from beb7cbbdcb68a786476040ef5cfc080072ab0243 to current master (1fe375469b55eb3059d59c6fc0a0629b6b6e4337) and it appears that the module was not functioning as expected anymore. Invoices were not generated, order statuses not changed and the following error occurs when running `bin/magento aune:autoinvoice:process`

`Notice: Undefined variable: email in vendor/aune-io/magento2-autoinvoice/Helper/Data.php on line 79`

I then went to look at Stores -> Configuration -> Sales -> Sales and none of the configurations in that tab would not render anymore, resulting in a blank page with following error in logs:
``
[2021-08-18 20:13:54] main.CRITICAL: Notice: Undefined variable: email in vendor/aune-io/magento2-autoinvoice/Model/Adminhtml/System/Config/ProcessingRule.php on line 136 {"exception":"[object] (Exception(code: 0): Notice: Undefined variable: email in vendor/aune-io/magento2-autoinvoice/Model/Adminhtml/System/Config/ProcessingRule.php on line 136 at vendor/magento/framework/App/ErrorHandler.php:61)"} []
``

https://github.com/aune-io/magento2-autoinvoice/blob/5297ba7c993026fde2c63bca1e63104faef28406/Helper/Data.php#L79
https://github.com/aune-io/magento2-autoinvoice/blob/5297ba7c993026fde2c63bca1e63104faef28406/Model/Adminhtml/System/Config/ProcessingRule.php#L136

I managed to get it running normally by changing `$email` to `isset($email) ? $email : ''` on those two files Data.php:79 and ProcessingRule.php:136.

Perhaps some default values for `$email` has to be enforced? What would be the correct default?

**Comment by renatocason** [comment]
Hi @taskula,

I released version 2.1.3 that should fix this, let me know if that works for you.

Thanks,
Renato

**Comment by taskula** [comment]
This issue seems to be fixed, closing.
