### ISSUE TITLE
PHP 8.2 for Magento 2.4.6

### ISSUE THREAD

**Issue by wilfriedwolf** [aune-io/magento2-autoinvoice#28]
Hi there,

I am trying to upgrade a site. Whenever I'll succeed I'll make a PR?
Did someone already implement PHP 8.2 compatibility?

Best regards,

Willi

**Comment by nordcomputer** [comment]
is this still a thing?

**Comment by nordcomputer** [comment]
I just tested the extension with php 8.2 - it seems to work fine - so maybe it is enough to edit the composer file to include php 8.2. 
@renatocason are you still maintaining the repo? I could create a pull request for that...

**Comment by renatocason** [comment]
Hi @nordcomputer ,

Sure, if you create the PR I'll merge it and release a new version.

Thanks,
Renato

**Comment by nordcomputer** [comment]
@renatocason 
I created a pull request, but I think, it needs some testing, as I also tried to update the code to meet the current coding standard. I really would appreciate, if someone could have a look at it.

Pull-Request: https://github.com/aune-io/magento2-autoinvoice/pull/29

**Comment by renatocason** [comment]
Thank you for the contribution, @nordcomputer.
All looked good, I merged and created a new release: https://github.com/aune-io/magento2-autoinvoice/releases/tag/2.3.0

**Comment by nordcomputer** [comment]
Thank you @renatocason
I think this issue can get closed.
