### ISSUE TITLE
Change order State when auto invoice

### ISSUE THREAD

**Issue by Zalm** [aune-io/magento2-autoinvoice#3]
Hi there,
first of all, thank you for this great module.
I have a little problem with the statistics in the admin Dashboard.
Actually, when i run auto invoice, the invoice is generated, the order status is updated but not the order state (column state of the sales_order table)
This causes the admin dashboard don't update the order count.

Example : 
1) I have a new order : state="new" status="pending"
2) I run autoInvoice : state="new" status="complete"
3) In the dashboard, i can't see this order agreggated.
The order table should be : state="complete" status="complete"

Can you please tell me if it's normal and if i should configure something?

For now, i updated the following file : /vendor/aune-io/magento2-autoinvoice/Model/InvoiceProcess.php line 116 , i just added this line : 
	$order->setState($item->getDestinationStatus());

thank you

**Comment by renatocason** [comment]
Hi @Zalm ,

Thanks for using the extension!
It's correct, the state should be updated as well as the status. I just pushed a fix for the issue, it's not retroactive... But it will prevent this from happening in the future.
Would you be able to test it out as well? If you can confirm it works, I will proceed and create a new release.

Thanks,
Renato

**Comment by Zalm** [comment]
Hi @renatocason , thank you! I confirm it works well on my project :)

**Comment by renatocason** [comment]
Hi @Zalm ,

Thanks for confirming, new release created!

Regards,
Renato
